package com.bit.armdcrf.dao;

import com.bit.armdcrf.model.Imgdata;
import java.util.List;

public interface ImgdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImgData
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImgData
     *
     * @mbggenerated
     */
    int insert(Imgdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImgData
     *
     * @mbggenerated
     */
    Imgdata selectByPrimaryKey(Integer id);


    List<Imgdata> selectByPatientid(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImgData
     *
     * @mbggenerated
     */
    List<Imgdata> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ImgData
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Imgdata record);
}